### ISSUE TITLE
Compilation error on ARM64EC after updating to 3.5.1

### ISSUE THREAD

**Issue by Benualdo** [redorav/hlslpp#88]
Hi,

I was previously using 3.4 and decided to update to 3.5.1 so as to get the float4x4=>3x3 fix on AVX but the project is no more compiling with ARM64EC target. 

Problem is related to quaternions:

`1>extern\hlslpp\include\hlsl++\quaternion.h(309,11): warning C4002: too many arguments for function-like macro invocation '_mm_and_ps'
1>(compiling source file 'Precomp.cpp')
1>extern\hlslpp\include\hlsl++\quaternion.h(309,11): error C2059: syntax error: ')'
1>(compiling source file 'Precomp.cpp')
2>hlslpp\include\hlsl++\quaternion.h(309,11): warning C4002: too many arguments for function-like macro invocation '_mm_and_ps'
2>(compiling source file 'Precomp.cpp')
2>extern\hlslpp\include\hlsl++\quaternion.h(309,11): error C2059: syntax error: ')'
2>(compiling source file 'Precomp.cpp')
1>extern\hlslpp\include\hlsl++\quaternion.h(309,11): error C2664: 'uint128_t __S128(const __m128)': cannot convert argument 1 from 'const uint32_t' to 'const __m128'
1>(compiling source file 'Precomp.cpp')
1>    extern\hlslpp\include\hlsl++\quaternion.h(309,11):
1>    '__m128::__m128': no overloaded function could convert all the argument types
1>        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\xmmintrin.h(75,2):
1>        could be '__m128::__m128(__m128 &&)'`

Full compilation log here:
[ARM64EC.txt](https://github.com/user-attachments/files/17128991/ARM64EC.txt)

Thanks

**Comment by redorav** [comment]
Hmm one thing that is confusing me is that it's using x64 intrinsics in your ARM build? How is that set up?

**Comment by Benualdo** [comment]
Yeah **defined(_M_ARM64EC)** is missing in case of ARM64EC build. Adding it fixes the issue. 

![{5F66BB03-4804-44C1-B6F5-65F542EDCC50}](https://github.com/user-attachments/assets/29615993-c7b1-47ab-9d97-6971fcb5fa57)

**Comment by Benualdo** [comment]
I know for sure I did not have the issue with 3.4 (my CI/CD would have complained) but havent investigated why exactly.

**Comment by redorav** [comment]
Ok I can take a look this evening

**Comment by redorav** [comment]
I fixed it with this e9fa5c9e07f63f8c8ade82193e752f01c4760e43 but also I think your fix is more correct. We probably want NEON intrinsics even in this transitional mode. I'll close this and accept the PR
